### ISSUE TITLE
TypeError in popup.js

### ISSUE THREAD

**Issue by Mohron** [Morta1/idleon-data-extractor#1]
Looks like there's an assumption that the account has 9 players. I was able to fix it by changing line 146-147:
```javascript
  const money = ['MoneyBANK', 'Money_0', 'Money_1', 'Money_2', 'Money_3', 'Money_4', 'Money_5', 'Money_6', 'Money_7', 'Money_8'].reduce((res, moneyInd) =>
    (res + fields[moneyInd] ? parseInt(fields[moneyInd].integerValue) : 0), 0);
```

![image](https://user-images.githubusercontent.com/3623122/131198931-08347d94-c122-465e-85fc-1271e536bdf3.png)

**Comment by Morta1** [comment]
Thanks for pointing it out!
