### ISSUE TITLE
Unable to fetch data

### ISSUE THREAD

**Issue by JigglesTheFett** [Morta1/idleon-data-extractor#3]
After loading the extension and attempting to fetch the data, the site itself tells me 'Please make sure you have the newest version of the extractor installed'. But the stack trace is as follows:
Uncaught Error: Extension context invalidated.
Context
https://www.legendsofidleon.com/ytGl5oc/
Stack Trace
src/inject.js:13 (anonymous function)

"const s = document.createElement("script");
s.src = chrome.runtime.getURL("src/injected.js");
s.onload = function () {
  this.remove();
};
(document.head || document.documentElement).appendChild(s);
chrome.storage.local.clear();

window.addEventListener(
  "globalData",
  (event) => {
    const { name, data } = event.detail;
    chrome.storage.local.get('globalData', async (result) => {
      if (!chrome.runtime.lastError) {
        await chrome.storage.local.set({ 'globalData': { ...result.globalData, [name]: data } });
      }
    });
  },
  false
);"

**Comment by Morta1** [comment]
Sorry for the delay, but have you tried re-installing the extension?

**Comment by Morta1** [comment]
The web version is currently not working, so I'll close this issue for now.
