### ISSUE TITLE
TypeError after World 3 Update

### ISSUE THREAD

**Issue by Mohron** [Morta1/idleon-data-extractor#4]
> Uncaught TypeError: Cannot read properties of undefined (reading 'd')
> 
> Context
> https://www.legendsofidleon.com/ytGl5oc/
> 
> Stack Trace
> src/injected.js:79 (anonymous function)
![image](https://user-images.githubusercontent.com/3623122/143906141-94cca869-8564-40d4-8b52-e6bb96335de6.png)

**Comment by Morta1** [comment]
Working on a new solution.
